import type { ExpoConfig } from 'expo/config';

// Dynamic config so we can read Supabase credentials from .env at build time.
// The values land in Constants.expoConfig.extra — never hardcode keys in source.
const config: ExpoConfig = {
  name: 'Kratos',
  slug: 'kratos',
  version: '1.0.0',
  orientation: 'portrait',
  icon: './assets/images/icon.png',
  scheme: 'kratos',
  userInterfaceStyle: 'automatic',
  ios: {
    bundleIdentifier: 'com.dhruvshah.kratos',
    // Build number (CFBundleVersion). Bumped to 2 after Apple rejected build 1
    // (1.0.0(1)) on upload — a rejected build number can't be reused. Increment
    // this on every new binary for the same marketing version.
    buildNumber: '2',
    // Apple Development Team for code signing. Declared here so a prebuild bakes
    // DEVELOPMENT_TEAM into the generated Xcode project instead of us hand-editing
    // the gitignored ios/*.pbxproj (which a prebuild would wipe). Free Personal
    // Team TUR974K866 (7-day cert). This is the Expo config schema's own key
    // (ios.appleTeamId) — expo-build-properties has no developmentTeam option in v57.
    appleTeamId: 'TUR974K866',
    // No ios.icon override — the top-level icon.png (LED barbell, generated by
    // scripts/build-app-icons.ts) applies everywhere.
    infoPlist: {
      // MUST be false: the app sets the status-bar style globally with
      // expo-status-bar (<StatusBar style={…}> in _layout), which goes through
      // RCTStatusBarManager — and that module *requires* this key to be NO or it
      // throws at launch ("RCTStatusBarManager module requires that the
      // UIViewControllerBasedStatusBarAppearance key in the Info.plist is set to
      // NO"). The old YES was for react-native-screens' per-screen
      // `statusBarStyle`, but the app only ever wants ONE theme-derived style, so
      // that Stack option was dropped in favour of the global one — which also
      // keeps the sign-in screen (rendered outside the Stack) theme-aware.
      // NOTE: ios/ is gitignored and not regenerated on every build, so
      // ios/Kratos/Info.plist carries the same value; keep the two in sync.
      UIViewControllerBasedStatusBarAppearance: false,
      // Export-compliance declaration (App Store): the app uses only standard
      // HTTPS/TLS (Supabase + the transcribe/parse edge functions) — no custom or
      // non-exempt cryptography. Declaring this here answers the encryption question
      // at build time so every upload skips the manual ITSAppUsesNonExemptEncryption
      // prompt in App Store Connect. false = exempt (standard encryption only).
      ITSAppUsesNonExemptEncryption: false,
      // Apple's SERVER-SIDE upload validator (stricter than Xcode's local check)
      // rejected build 1.0.0(1) on 2026-08-16 with ITMS-90683 for these two: linked
      // SDKs reference the Speech Recognition API (expo-speech-recognition) and the
      // Photo Library API (image stack, e.g. SDWebImage via expo-image). The app does
      // not actively use either, but Apple requires the purpose string whenever the
      // API is *referenced* ("your app might not use these APIs, a purpose string is
      // still required"). Suppressing them fails the upload — they MUST be present.
      NSSpeechRecognitionUsageDescription:
        'Allow Kratos to transcribe your speech so you can log sets by voice.',
      NSPhotoLibraryUsageDescription:
        'Allow Kratos to save images to your photo library.',
    },
  },
  android: {
    adaptiveIcon: {
      backgroundColor: '#020609', // color.bg — matches the generated background image
      foregroundImage: './assets/images/android-icon-foreground.png',
      backgroundImage: './assets/images/android-icon-background.png',
    },
    predictiveBackGestureEnabled: false,
  },
  web: {
    output: 'static',
    favicon: './assets/images/favicon.png',
  },
  plugins: [
    // MUST stay FIRST: Expo runs withInfoPlist mods in REVERSE of this array's
    // order, so listing this first makes it run LAST — after expo-audio has added
    // its UIBackgroundModes 'audio'. It then strips that unneeded key (Kratos only
    // records in the foreground) and any stray unused motion string. See the file.
    './plugins/withIosPrivacyCleanup',
    'expo-router',
    [
      'expo-splash-screen',
      {
        // The app is single-theme dark (LED instrument) — the splash must be
        // too, or cold start opens with a white flash before first paint.
        backgroundColor: '#020609',
        image: './assets/images/splash-icon.png',
        imageWidth: 104,
      },
    ],
    // NOTE: expo-speech-recognition's config plugin is intentionally NOT listed.
    // The shipping voice path is cloud ASR (expo-audio → the `transcribe` edge
    // function); on-device speech recognition (src/lib/stt.ts) is unreachable dead
    // code. Declaring NSSpeechRecognitionUsageDescription for a feature that never
    // runs is an App Store rejection risk (a usage string with no corresponding
    // functionality), so the plugin is dropped. The microphone permission string
    // the live recorder needs is supplied by expo-audio below.
    // Audio recording for cloud ASR (design "Voice Logging" 1a): the recorder
    // captures a clip that the `transcribe` edge function sends to gpt-transcribe.
    // (expo-speech-recognition also declares mic usage; both strings are harmless.)
    [
      'expo-audio',
      {
        microphonePermission: 'Allow Kratos to record your voice to log sets and build routines.',
      },
    ],
    // Apple Health gap-fill: read-only import of strength sessions the user did
    // but forgot to log (src/lib/healthkit.ts → src/data/healthImport.ts). We
    // only ever READ, so just NSHealthShareUsageDescription — no update string,
    // no background delivery. HealthKit is iOS-only; Kratos ships iOS-only too.
    [
      '@kingstinct/react-native-healthkit',
      {
        NSHealthShareUsageDescription:
          'Kratos reads your strength-training sessions from Apple Health to fill in days you worked out but forgot to log.',
        // Kratos is read-only in practice, BUT the HealthKit entitlement itself
        // permits writing, so Apple's upload validator HARD-BLOCKS the build
        // (error 90683) unless an Update usage string is present — even for APIs
        // the app never calls ("While your app might not use these APIs, a purpose
        // string is still required."). Suppressing it (the old `false`) failed the
        // upload on 2026-08-16. This string is required to ship; it is not a 5.1.3
        // problem (declaring a validator-mandated capability isn't misuse).
        NSHealthUpdateUsageDescription:
          'Allow Kratos to save workouts you log to Apple Health.',
        background: false,
      },
    ],
  ],
  experiments: {
    typedRoutes: true,
    reactCompiler: true,
  },
  extra: {
    supabaseUrl: process.env.SUPABASE_URL ?? '',
    supabaseAnonKey: process.env.SUPABASE_ANON_KEY ?? '',
  },
};

export default config;
