import type { ExpoConfig } from 'expo/config';

// Dynamic config so we can read Supabase credentials from .env at build time.
// The values land in Constants.expoConfig.extra — never hardcode keys in source.
const config: ExpoConfig = {
  name: 'RepVoice',
  slug: 'repvoice',
  version: '1.0.0',
  orientation: 'portrait',
  icon: './assets/images/icon.png',
  scheme: 'repvoice',
  userInterfaceStyle: 'automatic',
  ios: {
    bundleIdentifier: 'com.dhruvshah.repvoice',
    // Apple Development Team for code signing. Declared here so a prebuild bakes
    // DEVELOPMENT_TEAM into the generated Xcode project instead of us hand-editing
    // the gitignored ios/*.pbxproj (which a prebuild would wipe). Free Personal
    // Team TUR974K866 (7-day cert). This is the Expo config schema's own key
    // (ios.appleTeamId) — expo-build-properties has no developmentTeam option in v57.
    appleTeamId: 'TUR974K866',
    // No ios.icon override — the top-level icon.png (LED barbell, generated by
    // scripts/build-app-icons.ts) applies everywhere.
    infoPlist: {
      // react-native-screens requires this YES to let a native screen set the
      // status-bar style (we set statusBarStyle: 'light' on the Stack in _layout).
      // Expo defaults it to NO, which makes RNS throw a fatal red-screen assertion.
      UIViewControllerBasedStatusBarAppearance: true,
    },
  },
  android: {
    adaptiveIcon: {
      backgroundColor: '#020609', // color.bg — matches the generated background image
      foregroundImage: './assets/images/android-icon-foreground.png',
      backgroundImage: './assets/images/android-icon-background.png',
      monochromeImage: './assets/images/android-icon-monochrome.png',
    },
    predictiveBackGestureEnabled: false,
  },
  web: {
    output: 'static',
    favicon: './assets/images/favicon.png',
  },
  plugins: [
    'expo-router',
    [
      'expo-splash-screen',
      {
        // The app is single-theme dark (LED instrument) — the splash must be
        // too, or cold start opens with a white flash before first paint.
        backgroundColor: '#020609',
        image: './assets/images/splash-icon.png',
        imageWidth: 104,
      },
    ],
    // On-device STT for voice logging (Phase 2) — needs a config plugin for
    // the native mic/speech-recognizer permission strings.
    [
      'expo-speech-recognition',
      {
        microphonePermission: 'Allow RepVoice to use the microphone to log sets by voice.',
        speechRecognitionPermission: 'Allow RepVoice to use speech recognition to log sets by voice.',
      },
    ],
  ],
  experiments: {
    typedRoutes: true,
    reactCompiler: true,
  },
  extra: {
    supabaseUrl: process.env.SUPABASE_URL ?? '',
    supabaseAnonKey: process.env.SUPABASE_ANON_KEY ?? '',
  },
};

export default config;
