import type { ExpoConfig } from 'expo/config';

// Dynamic config so we can read Supabase credentials from .env at build time.
// The values land in Constants.expoConfig.extra — never hardcode keys in source.
const config: ExpoConfig = {
  name: 'Kratos',
  slug: 'kratos',
  version: '1.0.0',
  orientation: 'portrait',
  icon: './assets/images/icon.png',
  scheme: 'kratos',
  userInterfaceStyle: 'automatic',
  ios: {
    bundleIdentifier: 'com.dhruvshah.kratos',
    // Apple Development Team for code signing. Declared here so a prebuild bakes
    // DEVELOPMENT_TEAM into the generated Xcode project instead of us hand-editing
    // the gitignored ios/*.pbxproj (which a prebuild would wipe). Free Personal
    // Team TUR974K866 (7-day cert). This is the Expo config schema's own key
    // (ios.appleTeamId) — expo-build-properties has no developmentTeam option in v57.
    appleTeamId: 'TUR974K866',
    // No ios.icon override — the top-level icon.png (LED barbell, generated by
    // scripts/build-app-icons.ts) applies everywhere.
    infoPlist: {
      // MUST be false: the app sets the status-bar style globally with
      // expo-status-bar (<StatusBar style={…}> in _layout), which goes through
      // RCTStatusBarManager — and that module *requires* this key to be NO or it
      // throws at launch ("RCTStatusBarManager module requires that the
      // UIViewControllerBasedStatusBarAppearance key in the Info.plist is set to
      // NO"). The old YES was for react-native-screens' per-screen
      // `statusBarStyle`, but the app only ever wants ONE theme-derived style, so
      // that Stack option was dropped in favour of the global one — which also
      // keeps the sign-in screen (rendered outside the Stack) theme-aware.
      // NOTE: ios/ is gitignored and not regenerated on every build, so
      // ios/Kratos/Info.plist carries the same value; keep the two in sync.
      UIViewControllerBasedStatusBarAppearance: false,
      // Export-compliance declaration (App Store): the app uses only standard
      // HTTPS/TLS (Supabase + the transcribe/parse edge functions) — no custom or
      // non-exempt cryptography. Declaring this here answers the encryption question
      // at build time so every upload skips the manual ITSAppUsesNonExemptEncryption
      // prompt in App Store Connect. false = exempt (standard encryption only).
      ITSAppUsesNonExemptEncryption: false,
    },
  },
  android: {
    adaptiveIcon: {
      backgroundColor: '#020609', // color.bg — matches the generated background image
      foregroundImage: './assets/images/android-icon-foreground.png',
      backgroundImage: './assets/images/android-icon-background.png',
      monochromeImage: './assets/images/android-icon-monochrome.png',
    },
    predictiveBackGestureEnabled: false,
  },
  web: {
    output: 'static',
    favicon: './assets/images/favicon.png',
  },
  plugins: [
    'expo-router',
    [
      'expo-splash-screen',
      {
        // The app is single-theme dark (LED instrument) — the splash must be
        // too, or cold start opens with a white flash before first paint.
        backgroundColor: '#020609',
        image: './assets/images/splash-icon.png',
        imageWidth: 104,
      },
    ],
    // On-device STT for voice logging (Phase 2) — needs a config plugin for
    // the native mic/speech-recognizer permission strings.
    [
      'expo-speech-recognition',
      {
        microphonePermission: 'Allow Kratos to use the microphone to log sets by voice.',
        speechRecognitionPermission: 'Allow Kratos to use speech recognition to log sets by voice.',
      },
    ],
    // Audio recording for cloud ASR (design "Voice Logging" 1a): the recorder
    // captures a clip that the `transcribe` edge function sends to gpt-transcribe.
    // (expo-speech-recognition also declares mic usage; both strings are harmless.)
    [
      'expo-audio',
      {
        microphonePermission: 'Allow Kratos to record your voice to log sets and build routines.',
      },
    ],
    // Apple Health gap-fill: read-only import of strength sessions the user did
    // but forgot to log (src/lib/healthkit.ts → src/data/healthImport.ts). We
    // only ever READ, so just NSHealthShareUsageDescription — no update string,
    // no background delivery. HealthKit is iOS-only; Kratos ships iOS-only too.
    [
      '@kingstinct/react-native-healthkit',
      {
        NSHealthShareUsageDescription:
          'Kratos reads your strength-training sessions from Apple Health to fill in days you worked out but forgot to log.',
        background: false,
      },
    ],
  ],
  experiments: {
    typedRoutes: true,
    reactCompiler: true,
  },
  extra: {
    supabaseUrl: process.env.SUPABASE_URL ?? '',
    supabaseAnonKey: process.env.SUPABASE_ANON_KEY ?? '',
  },
};

export default config;
