// Bottom nav. The "Rolling Weeks" redesign reduced it to three tabs
// (HOME · ROUTINES · ACCOUNT) — the calendar heatmap and history now live inside
// Home, so those tabs retired. Active tab carries the LED underline. Presentational
// only — each caller passes its own onPress per tab. A tab with no onPress is the
// active/no-op one and reads dim.
import { router } from 'expo-router';
import { Pressable, Text, View } from 'react-native';
import { font, radius } from '@/theme/tokens';
import { useTheme } from '@/theme/ThemeProvider';

type Tab = { key: string; label: string; onPress?: () => void };

// The canonical 3-tab set. `active` is the current screen's key; the other two get a
// router.replace() so depth stays 1 (top-level tabs don't stack — see feedback #10).
export function HomeTabBar({ active }: { active: 'home' | 'routines' | 'account' }) {
  // `route` is a literal app path; cast because expo-router's typed-route table is
  // regenerated by the dev server/export and may not yet include a newly-added screen.
  const nav = (key: string, route: '/' | '/routines' | '/settings') =>
    key === active ? undefined : () => router.replace(route as '/');
  return (
    <TabBar
      active={active}
      tabs={[
        { key: 'home', label: 'HOME', onPress: nav('home', '/') },
        { key: 'routines', label: 'ROUTINES', onPress: nav('routines', '/routines') },
        { key: 'account', label: 'ACCOUNT', onPress: nav('account', '/settings') },
      ]}
    />
  );
}

export function TabBar({ active, tabs }: { active: string; tabs: Tab[] }) {
  const { color, shadow } = useTheme();
  return (
    <View
      style={{
        flexDirection: 'row',
        borderTopWidth: 1,
        borderTopColor: color.line,
        backgroundColor: color.s1,
        paddingTop: 12,
        paddingBottom: 26,
      }}
    >
      {tabs.map((t) => {
        const on = t.key === active;
        return (
          <Pressable
            key={t.key}
            onPress={t.onPress}
            disabled={!t.onPress}
            style={{ flex: 1, alignItems: 'center' }}
          >
            <Text
              style={{
                fontFamily: on ? font.numBold : font.numSemibold,
                fontSize: 13,
                color: on ? color.acc : color.t3,
              }}
            >
              {t.label}
            </Text>
            {on && (
              <View
                style={{
                  width: 20,
                  height: 2,
                  backgroundColor: color.acc,
                  borderRadius: radius.pill,
                  marginTop: 4,
                  ...shadow.glowSm,
                }}
              />
            )}
          </Pressable>
        );
      })}
    </View>
  );
}
